#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dx11=enabled \
    -Dintrospection=enabled \
    -Ddocs=false \
    -Ddbus_daemon=/usr/bin/dbus-daemon \
    output

ninja -C output
ninja -C output install
