#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -p1 < "$patch"
done

pkg-config --exists wayland && wayland=true

# Yes this is somewhat stupid, but it doesn't build otherwise.
sed "/assert(enable_rfkill/d" meson.build > _
mv -f _ meson.build

# NOTE: We are disabling rfkill, which may or may not cause problems???
meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib/gnome-settings-daemon \
    -Dsysconfdir=/etc \
    -Dlocalstatedir=/var \
    -Dsystemd=false \
    -Dalsa=true \
    -Dcolord=false \
    -Dcups=false \
    -Dnetwork_manager=false \
    -Dsmartcard=false \
    -Drfkill=false \
    -Dwacom=false \
    -Dwayland=false \
    -Dwwan=false \
    output

ninja -C output
ninja -C output install
