#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=plain \
    -Dpython=python3 \
    -Dtests=false \
    output

ninja -C output
ninja -C output install
