#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < gsh.patch

meson setup \
    -Dprefix=/usr \
    -Dsystemd=false \
    -Dman=false \
    -Dtests=false \
    output

ninja -C output
ninja -C output install
