#!/bin/sh -e

export DESTDIR="$1"

# Disable nls.
: > po/meson.build

# TODO: add check for gtk4

pkg-config --exists gobject-introspection-1.0 && gi=true
command -v vala && vapi=true

meson setup \
    -Dprefix=/usr \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Dintrospection="${gi:-false}" \
    -Dvapi="${vapi:-false}" \
    -Dgtk4=false \
    -Dgtk_doc=false \
    -Dsystemd=disabled \
    -Dssh_agent=false \
    output

ninja -C output
ninja -C output install
