#!/bin/sh -e

export DESTDIR="$1"

: > tests/meson.build

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=plain \
    output

ninja -C output
ninja -C output install
