#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dintrospection=enabled \
    -Dexamples=false \
    -Dgtk_doc=false \
    -Dtests=false \
    output

ninja -C output
ninja -C output install
