#!/bin/sh -e

export DESTDIR="$1"

sed "/subdir('test/d" meson.build > _
mv -f _ meson.build

# Fix meson_options.txt for muon
sed -E "s/'(true|false)'/\1/" meson_options.txt > _
mv -f _ meson_options.txt

meson setup \
    -Dprefix=/usr \
    -Dsystem_pid_file=/run/dbus/dbus.pid \
    output

ninja -C output
ninja -C output install

mkdir -p "$1/etc/sv/dbus"
cp -f dbus.run "$1/etc/sv/dbus/run"
ln -s /run/runit/supervise.dbus "$1/etc/sv/dbus/supervise"
