#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dlocalstatedir=/var \
    -Dbuildtype=plain \
    -Dinstalled_tests=false \
    output

ninja -C output
ninja -C output install
