#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --bindir=/usr/bin \
    --enable-hwdb \
    --enable-blkid=auto \
    --disable-introspection

make
make install

# Install runit service.
install -Dm755 udevd.run         "$1/etc/sv/udevd/run"
ln -s /run/runit/supervise.udevd "$1/etc/sv/udevd/supervise"
