#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    output

ninja -C output
ninja -C output install

install -Dm644 io.elementary.desktop.agent-polkit.desktop \
    -t "$1/etc/xdg/autostart"
