#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dgtk=true \
    -Dintrospection=enabled \
    -Dvapi=true \
    -Dtests=true \
    -Dgtk_doc=false \
    output

ninja -C output
ninja -C output install
