#!/bin/sh -e

export DESTDIR="$1"

sed '/systemd_dep/d' meson.build > _
mv -f _ meson.build
sed '/systemd_dep/d' data/meson.build > _
mv -f _ data/meson.build

meson setup \
    -Dprefix=/usr \
    output

ninja -C output
ninja -C output install
