#!/bin/sh -e

export DESTDIR="$1"

sed "/add_subdirectory(tests)/d" CMakeLists.txt > _
mv -f _ CMakeLists.txt

cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DBUILD_SHARED_LIBS=ON

cmake --build   build
cmake --install build
