#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dsystemd=false \
    output

ninja -C output
ninja -C output install

# Remove unused stuff
rm -rf "$1/usr/share/applications/gala-wayland.desktop"
