#!/bin/sh -e

export DESTDIR="$1"

# Invalid vala syntax, new release will solve this
sed 's/Variant\[2\] t/Variant\[\] t/g' src/Views/LocationPanel.vala > _
mv -f _ src/Views/LocationPanel.vala

meson setup \
    -Dprefix=/usr \
    output

ninja -C output
ninja -C output install
